# Generated by Django 4.1.7 on 2023-03-09 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coming', '0012_remove_coming_phone'),
        ('Agreement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AddField(
            model_name='agreement',
            name='coming_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Coming.coming'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agreement',
            name='price_transport',
            field=models.IntegerField(default=0),
        ),
    ]
