# Generated by Django 4.1.7 on 2023-03-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agreement', '0002_alter_agreement_options_agreement_coming_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
