# Generated by Django 4.1.7 on 2023-03-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agreement', '0003_agreement_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
