# Generated by Django 4.1.7 on 2023-03-10 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agreement', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='service_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Agreement.service'),
        ),
    ]
