# Generated by Django 4.1.7 on 2023-03-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cashbox', '0006_cashbox_create_date_time'),
        ('Agreement', '0007_agreement_service_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='cashbox',
            field=models.ManyToManyField(to='Cashbox.cashbox'),
        ),
    ]
