# Generated by Django 4.1.7 on 2023-03-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agreement', '0008_agreement_cashbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='cashbox',
            new_name='cashboxes',
        ),
    ]
