# Generated by Django 4.1.7 on 2023-03-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cashbox', '0006_cashbox_create_date_time'),
        ('Agreement', '0009_rename_cashbox_agreement_cashboxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='cashboxes',
            field=models.ManyToManyField(blank=True, to='Cashbox.cashbox'),
        ),
    ]
