# Generated by Django 4.1.7 on 2023-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cashbox', '0008_cashbox'),
        ('Agreement', '0011_remove_agreement_cashboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='cashboxes',
            field=models.ManyToManyField(blank=True, to='Cashbox.cashbox'),
        ),
    ]
