# Generated by Django 4.1.7 on 2023-05-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0005_personal_status_fk'),
        ('Agreement', '0012_agreement_cashboxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='upp',
            field=models.ManyToManyField(to='Personal.personal'),
        ),
    ]
