# Generated by Django 4.1.7 on 2023-05-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agreement', '0013_agreement_upp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='upp',
        ),
    ]
