# Generated by Django 4.1.7 on 2023-05-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='data',
        ),
    ]
