# Generated by Django 4.1.7 on 2023-02-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=12)),
                ('call', models.IntegerField(blank=True, null=True)),
                ('upp', models.IntegerField(blank=True, null=True)),
                ('theme', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('create_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
    ]
