# Generated by Django 4.1.7 on 2023-02-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coming', '0002_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coming',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Coming.theme'),
        ),
    ]
