# Generated by Django 4.1.7 on 2023-02-28 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Coming', '0003_alter_coming_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coming',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
