# Generated by Django 4.1.7 on 2023-02-28 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Coming', '0006_rename_theme_coming_theme_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Статус прихода',
                'verbose_name_plural': 'Статусы приходов',
            },
        ),
    ]
