# Generated by Django 4.1.7 on 2023-02-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coming', '0008_remove_coming_status_coming_status_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coming',
            old_name='create_date',
            new_name='create_date_time',
        ),
    ]
