# Generated by Django 4.1.7 on 2023-02-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coming', '0009_rename_create_date_coming_create_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coming',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
