# Generated by Django 4.1.7 on 2023-03-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_alter_client_phone'),
        ('Coming', '0010_alter_coming_create_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coming',
            name='client_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
            preserve_default=False,
        ),
    ]
