# Generated by Django 4.1.7 on 2023-03-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coming', '0011_coming_client_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coming',
            name='phone',
        ),
    ]
