# Generated by Django 4.1.7 on 2023-05-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coming', '0012_remove_coming_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coming',
            name='call',
        ),
    ]
