# Generated by Django 4.1.7 on 2023-05-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0005_personal_status_fk'),
        ('Coming', '0013_remove_coming_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='coming',
            name='call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Personal.personal', verbose_name='Оператор'),
        ),
    ]
