# Generated by Django 4.1.7 on 2023-05-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coming', '0015_rename_call_coming_call_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coming',
            name='upp',
        ),
    ]
