# Generated by Django 4.1.7 on 2023-02-28 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0003_personal_department_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPersone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус сотрудника',
                'verbose_name_plural': 'Статусы сотрудников',
            },
        ),
    ]
