# Generated by Django 4.1.7 on 2023-02-28 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0004_statuspersone'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='status_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Personal.statuspersone'),
            preserve_default=False,
        ),
    ]
