# Generated by Django 4.1.7 on 2023-03-16 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cashbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typepayment',
            options={'verbose_name': 'Тип платежа', 'verbose_name_plural': 'Типы платежей'},
        ),
        migrations.AlterField(
            model_name='typepayment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
