# Generated by Django 4.1.7 on 2023-03-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cashbox', '0002_alter_typepayment_options_alter_typepayment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypePayment',
        ),
    ]
