# Generated by Django 4.1.7 on 2023-03-16 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cashbox', '0003_delete_typepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип платежа',
                'verbose_name_plural': 'Типы платежей',
            },
        ),
    ]
