# Generated by Django 4.1.7 on 2023-03-16 22:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cashbox', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('money', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Деньги')),
                ('type_payment_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cashbox.typepayment')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Касса',
            },
        ),
    ]
