# Generated by Django 4.1.7 on 2023-03-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cashbox', '0005_cashbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
