# Generated by Django 4.1.7 on 2023-03-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agreement', '0011_remove_agreement_cashboxes'),
        ('Cashbox', '0006_cashbox_create_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cashbox',
        ),
    ]
