# Generated by Django 4.1.7 on 2023-03-18 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cashbox', '0007_delete_cashbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('money', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Деньги')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('type_payment_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cashbox.typepayment')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Касса',
            },
        ),
    ]
