# Generated by Django 4.1.7 on 2023-05-09 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cashbox', '0008_cashbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMoney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип денег',
                'verbose_name_plural': 'Типы денег',
            },
        ),
    ]
