# Generated by Django 4.1.7 on 2023-05-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cashbox', '0009_typemoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='type_money',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Cashbox.typemoney'),
            preserve_default=False,
        ),
    ]
