# Generated by Django 4.1.7 on 2023-05-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cashbox', '0010_cashbox_type_money'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbox',
            old_name='type_money',
            new_name='type_money_fk',
        ),
    ]
