# Generated by Django 4.1.7 on 2023-05-11 08:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Ключ')),
                ('value', models.CharField(max_length=250, verbose_name='Значение')),
                ('app_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.app', verbose_name='Приложение')),
            ],
            options={
                'verbose_name': 'Базовая настройка',
                'verbose_name_plural': 'Базовые настройки',
            },
        ),
    ]
