# Generated by Django 4.1.7 on 2023-05-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseSetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basesetting',
            name='description',
            field=models.CharField(default=1, max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
